name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Welcome message
          run: echo "My firt programme with GH Actions"
        
        - name: List files
          run: ls
        
        - name: Readfile
          run: cat README.md
        